

import enum
class Column (enum.Enum):
    ''' Enum to hold string constants to refer to columns of the log file '''
    batch = "batch"
    # workState = "WorkSM"
    workState =  "Workflow" 
    # dryState = "DrySM" 
    dryState = "SmDrying"
    timeStamp = "TimeStamp"
    time = "TimeSec"
    elapsedTime = "Time (min)"
    faultCode = "FaultCode"
    scale = "SCALE"
    digitalOut = "DigOut"
    digatlOut_oldName = "Dout_0_19" #past name from script, kept if script needs to be run on past data
    PT03 = "PT03"
    PT05 = "PT05"
    PT06 = "PT06"
    PT07 = "PT07"
    PT08 = "PT08"
    PT09 = "PT09"
    FS01 = "FS01"
    periPumpFlow = "PeriPumpFlow"
    pt01Trend = "PT01"
    pt02Trend = "PT02"
    pt05Trend = "PT05_TREND"
    pt08Trend = "PT08_9_TREND"

    #Added PT01, PT02, TT04, TT05, TT06, TT07, MFC01, MFC02, DPT01a, DPT01b - Payton
    TT04 = "TT04"
    TT05 = "TT05"
    TT06 = "TT06"
    TT07 = "TT07"
    MFC01 = "MFC01"
    MFC02 = "MFC02"
    DPT01a = "DPT01a"
    DPT01b = "DPT01b"

    #added MCF01_P, PT10 which replace PT03 in PMA data - Henry 
    MFC01_P = "MFC01_P"
    PT10 = "PT10"

class WorkState (enum.Enum):
    ''' Enum to hold string constants to refer to the different possible states of WorkSM used in the statistics. '''
    runDeflectorDown = "Wrk_runDeflectorDownSM"
    unlockDoor = "Wrk_UnlockDoor"
    runDeflectorUp = "Wrk_runDeflectorUpSM"
    runCassetteCheck = "Wrk_runCassettecheckSM"
    runEnclosureCheck = "Wrk_runEnclosureCheckSM"
    runAerosolCheck = "Wrk_runAerosolCheckSM"
    runDispPrecheck = "Wrk_runDispPrecheckSM"
    runDrying = "Wrk_runDryingSM"
    runDispIntegrity = "Wrk_runDispIntegritySM"
    stopped = "Stopped"
class DryState (enum.Enum):
    ''' Enum to hold string constants to refer to the different possible states of DrySM used in the statistics. '''
    drying = "Drying"
    dryingGasContinue = "DryingGasContinue"
    priming = "Priming"
class Output (enum.Enum):
    ''' Enum to hold keys and constant values for the output '''
    error = "N/A"
class SummaryKey (enum.Enum):
    ''' Enum to hold keys for the calculated summary values. '''
    batch_key = "Batch ID"
    batch_start_key = "Timestamp of batch start"
    batch_end_key = "Timestamp of batch end"
    fault_codes_key = "Unique non-zero fault codes"
    run_duration_key = "Run duration [minutes]"
    drying_duration_key = "Drying duration [minutes]"
    total_mass_processed_key = "Total mass processed [grams]"
    initial_mass_key = "Initial mass [grams]"
    enclosure_integrity_ending_pressure_key = "Enclosure integrity ending pressure [psig]"
    aerosol_integrity_ending_pressure_key = "Aerosol integrity ending pressure [psig]"
    pre_pdc_integrity_ending_pressure_key = "Pre PDC integrity ending pressure [psig]"
    pre_prd_integrity_average_leak_rate_key = "Pre PDC integrity average leak rate [SCCM]"
    initial_exhaust_temperature_spike_key6 = "Initial exhaust temperature spike (TT06) [" + u'\N{DEGREE SIGN}' + "C]"
    initial_exhaust_temperature_spike_key7 = "Initial exhaust temperature spike (TT07) [" + u'\N{DEGREE SIGN}' + "C]"
    minimum_exhaust_temperature_key6 = "Minimum exhaust temperature (TT06) [" + u'\N{DEGREE SIGN}' + "C]"
    minimum_exhaust_temperature_key7 = "Minimum exhaust temperature (TT07)  [" + u'\N{DEGREE SIGN}' + "C]"
    average_plasma_flow_rate_key = "Average plasma flow rate [mL/min]"
    peak_plasma_flow_rate_key = "Peak plasma flow rate [mL/min]"
    minimum_plenum_pressute_key = "Minimum plenum pressure [psig]"
    peak_plenum_pressure_key = "Peak plenum pressure [psig]"
    minimum_aerosol_pressure_key = "Minimum aerosol pressure [psig]"
    peak_aerosol_pressure_key = "Peak aerosol pressure [psig]"
    minimum_drying_chamber_pressure_pt08_key = "Minimum drying chamber pressure (PT08) [psig]"
    minimum_drying_chamber_pressure_pt09_key = "Minimum drying chamber pressure (PT09) [psig]"
    peak_drying_chamber_pressure_pt08_key = "Peak drying chamber pressure (PT08) [psig]"
    peak_drying_chamber_pressure_pt09_key = "Peak drying chamber pressure (PT09) [psig]"
    ending_exhaust_temperature_spike_tt06_key = "Ending exhaust temperature spike (TT06) [" + u'\N{DEGREE SIGN}' + "C]"
    ending_exhaust_temperature_spike_tt07_key = "Ending exhaust temperature spike (TT07) [" + u'\N{DEGREE SIGN}' + "C]"
    post_pdc_integrity_ending_pressure_key = "Post PDC integrity ending pressure [psig]"
    post_pdc_integrity_average_leak_rate_key = "Post PDC integrity average leak rate [mL/min]"

    #Added PT01, PT02, TT04, TT05, TT06, TT07, MFC01, MFC02, DPT01a, DPT01b - Payton
    pt01_trend_min_key = "PT01 minimum"
    pt01_trend_max_key = "PT01 maximum"
    pt01_trend_avg_key = "PT01 average"
    pt02_trend_min_key = "PT02 minimum"
    pt02_trend_max_key = "PT02 maximum"
    pt02_trend_avg_key = "PT02 average"
    pt05_trend_min_key = "PT05 trend minimum"
    pt05_trend_max_key = "PT05 trend maximum"
    pt05_trend_avg_key = "PT05 trend average"
    pt08_trend_min_key = "PDC Trend Minimum (PSI/minute)"
    pt08_trend_max_key = "PDC Trend Maximum (PSI/minute)"
    pt08_trend_avg_key = "PDC Trend Average (PSI/minute)"
    tt04_min_key = "TT04 Minimum"
    tt04_max_key = "TT04 Maximum"
    tt04_avg_key = "TT04 Average"
    tt05_min_key = "TT05 Minimum"
    tt05_max_key = "TT05 Maximum"
    tt05_avg_key = "TT05 Average"
    tt06_min_key = "TT06 Minimum"
    tt06_max_key = "TT06 Maximum"
    tt06_avg_key = "TT06 Average"
    tt07_min_key = "TT07 Minimum"
    tt07_max_key = "TT07 Maximum"
    tt07_avg_key = "TT07 Average"
    mfc01_min_key = "MFC01 Minimum"
    mfc01_max_key = "MFC01 Maximum"
    mfc01_avg_key = "MFC01 Average"
    mfc02_min_key = "MFC02 Minimum"
    mfc02_max_key = "MFC02 Maximum"
    mfc02_avg_key = "MFC02 Average"
    dpt01a_avg_key = "DPT01a Average"
    dpt01b_avg_key = "DPT01b Average"
    #equalibrium
    tt04E_min_key = "TT04 e Minimum"
    tt04E_max_key = "TT04 e Maximum"
    tt04E_avg_key = "TT04 e Average"
    tt04E_std_key = "TT04 e StDev"
    tt05E_min_key = "TT05 e Minimum"
    tt05E_max_key = "TT05 e Maximum"
    tt05E_avg_key = "TT05 e Average"
    tt05E_std_key = "TT05 e StDev"
    tt06E_min_key = "TT06 e Minimum"
    tt06E_max_key = "TT06 e Maximum"
    tt06E_avg_key = "TT06 e Average"
    tt06E_std_key = "TT06 e StDev"
    tt07E_min_key = "TT07 e Minimum"
    tt07E_max_key = "TT07 e Maximum"
    tt07E_avg_key = "TT07 e Average"
    tt07E_std_key = "TT07 e StDev"
    mfc01E_min_key = "MFC01 e Minimum"
    mfc01E_max_key = "MFC01 e Maximum"
    mfc01E_avg_key = "MFC01 e Average"
    mfc01E_std_key = "MFC01 e StDev"
    mfc02E_min_key = "MFC02 e Minimum"
    mfc02E_max_key = "MFC02 e Maximum"
    mfc02E_avg_key = "MFC02 e Average"
    mfc02E_std_key = "MFC02 e StDev"
    dpt01aE_avg_key = "DPT01a e Average"
    dpt01aE_std_key = "DPT01a e StDev"
    dpt01bE_avg_key = "DPT01b e Average"
    dpt01bE_std_key = "DPT01b e StDev"

